@startuml teste 

actor Usuario
actor Administrador

rectangle "VídeosON - VO" {
(Cadastro de Usuário) as RF1
(Login e Autenticação) as RF2
(Consumo de Vídeos) as RF3
(Controle de Interrupção) as RF4
(Verificação de Histórico) as RF5
(Consulta de Histórico) as RF6
(Publicação de Vídeos) as RF7
}

Usuario -- RF1
Usuario -- RF2
Usuario -- RF3
Usuario -- RF4
Usuario -- RF5
Usuario -- RF6
Administrador -- RF7

note right of RF5
Se vídeo já foi consumido, informar o usuário.
end note

note right of RF2
Validação de usuário e senha
end note

note right of RF4
Pode ser interrupção manual ou por falha do sistema
end note

@enduml
